#Spring name for configuration server
spring.application.name=transaction_service
#spring.data.mongodb.uri=mongodb+srv://ntt_access_proyects:sTBqd1peP3HFJgHa@nttdatabnkdb.g8qwtzr.mongodb.net/?retryWrites=true&w=majority&appName=NTTDataBnkDB
#spring.data.mongodb.uri=mongodb://localhost:27017/NTTBankingService
#server.port=8083
#ConfigServer connection
spring.config.import=configserver:
spring.cloud.config.uri=http://localhost:8888
#Connection URI to Account Service
#external.account.service.uri=http://localhost:8085/api/accounts
#Connection URI to Credit Service
#external.credit.service.uri=http://localhost:8585/api/v1/credits
#Connection URI to Client Service
#external.client.service.uri=http://localhost:8086/api/v1/customers
#Connection URI to Client Service
#external.card.service.uri=http://localhost:8090
# ========================
# Resilience4j CircuitBreaker
# ========================
#resilience4j.circuitbreaker.instances.transactionService.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.transactionService.eventConsumerBufferSize=10
#resilience4j.circuitbreaker.instances.transactionService.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.transactionService.minimumNumberOfCalls=5
#resilience4j.circuitbreaker.instances.transactionService.automaticTransitionFromOpenToHalfOpenEnabled=true
#resilience4j.circuitbreaker.instances.transactionService.waitDurationInOpenState=5s
#resilience4j.circuitbreaker.instances.transactionService.permittedNumberOfCallsInHalfOpenState=3
#resilience4j.circuitbreaker.instances.transactionService.slidingWindowSize=10
#resilience4j.circuitbreaker.instances.transactionService.slidingWindowType=COUNT_BASED
# ========================
# Resilience4j RateLimiter
# ========================
#resilience4j.ratelimiter.instances.transactionService.limitForPeriod=2
#resilience4j.ratelimiter.instances.transactionService.limitRefreshPeriod=5s
#resilience4j.ratelimiter.instances.transactionService.timeoutDuration=10s
#resilience4j.ratelimiter.instances.transactionService.registerHealthIndicator=true
#resilience4j.ratelimiter.instances.transactionService.eventConsumerBufferSize=100
# ========================
# Resilience4j TimeLimiter
# ========================
#resilience4j.timelimiter.instances.transactionService.timeoutDuration=2s
#resilience4j.timelimiter.instances.transactionService.cancelRunningFuture=true
# ========================
# Resilience4j Retry (comentado en YAML)
# ========================
# resilience4j.retry.instances.transactionService.maxRetryAttempts=5
# resilience4j.retry.instances.transactionService.waitDuration=10s
# ========================
# Resilience4j Bulkhead (comentado en YAML)
# ========================
# resilience4j.bulkhead.instances.transactionService.maxWaitDuration=5s
# resilience4j.bulkhead.instances.transactionService.maxConcurrentCalls=5
# ========================
# Resilience4j ThreadPoolBulkhead (comentado en YAML)
# ========================
# resilience4j.thread-pool-bulkhead.instances.transactionService.maxThreadPoolSize=1
# resilience4j.thread-pool-bulkhead.instances.transactionService.coreThreadPoolSize=1
# resilience4j.thread-pool-bulkhead.instances.transactionService.queueCapacity=1
